import Head from "next/head";
import index from "./home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Book World </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <index />
    </>
  );
}
