import Footer from "@/components/Home/Footer";
import HomePage from "@/components/Home/Home";
import NavBar from "@/components/NavBar/NavBar";
import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Book World </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <NavBar/>
       <HomePage/>
       <Footer/>

    </>
  );
}
